### ISSUE TITLE
App Graphics Preview

### ISSUE THREAD

**Issue by neynah** [dwrensha/acronymy#2]
What about either of these shapes? I haven't distributed the letters in any way yet but that's an option if you're interested. Also open to trying something completely different, just let me know what you're looking for. :)

![acronymy-preview2](https://cloud.githubusercontent.com/assets/855341/9395732/fb67a64c-4744-11e5-8206-2d8b7d16ed38.png)

**Comment by dwrensha** [comment]
I like this direction. The snowflake/web with floating ABC's seems especially appropriate.

**Comment by neynah** [comment]
Better?

![acronymy-preview3](https://cloud.githubusercontent.com/assets/855341/9399024/557e3c54-4763-11e5-9d3e-466157f141af.png)

**Comment by dwrensha** [comment]
Yeah, I'm happy with this.
